language: node_js
node_js:
  - "0.8"
  - "0.12"
  - "io.js"
matrix:
  include:
    - node_js: "0.10"
      env: BROWSER=true
before_install:
  - npm install -g npm@2.6
  - npm install -g karma-cli
before_script:
  - npm install karma-sauce-launcher
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - npm run coveralls
script:
  - npm test
  - "[ $BROWSER == false ] || npm run test-browser"
  # Karma sauce is limited to running about 5-7 browsers (or it will tiemout) at a time so we just run vendor by vendor here
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js --browsers CHROME_V26,CHROME_V35,CHROME_V40"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js --browsers FF_V3.6,FF_V4,FF_V11,FF_V35"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js --browsers SAFARI_V5,SAFARI_V6,SAFARI_V7,SAFARI_V8"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js --browsers OPERA_V11,OPERA_V12"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js --browsers IE_V7,IE_V8,IE_V9,IE_V10,IE_V11"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js --browsers ANDROID_V4"
env:
  matrix: BROWSER=false
